# uiua repl: https://www.uiua.org/pad?src=0_5_1__JCBUaW1lOiAgICAgIDcgIDE1ICAgMzAKJCBEaXN0YW5jZTogIDkgIDQwICAyMDAK4oavMl_CrzHiiaEo4ouV4oqhMSlyZWdleCIoXFxkKykiCklucHV0IOKGkAoKV2F5c1RvV2luIOKGkCAvKzzDl-KHjC4g4oehKzEKCkpvaW5OdW1iZXJzIOKGkCDiiaEo4ouV4pa94omgQCAu4pmt4qyaQCDiiaEo4o2Y4ouVKSkKCi_Dl-KJoShXYXlzVG9XaW7ijZjiip8p4o2JIElucHV0Cgovw5fiiaEoV2F5c1RvV2lu4o2Y4oqfKSDCpEpvaW5OdW1iZXJzIElucHV0Cg==

$ Time:      7  15   30
$ Distance:  9  40  200

↯2_¯1≡(⋕⊡1)regex"(\\d+)"
Input ←

WaysToWin ← /+<×⇌. ⇡+1

JoinNumbers ← ≡(⋕▽≠@ .♭⬚@ ≡(⍘⋕))

Solve ← /×≡(WaysToWin⍘⊟)

PartOne ← Solve⍉
PartTwo ← Solve¤JoinNumbers

PartOne Input
PartTwo Input
