# uiua repl: https://www.uiua.org/pad?src=0_6_1__JCAwIDMgNiA5IDEyIDE1CiQgMSAzIDYgMTAgMTUgMjEKJCAxMCAxMyAxNiAyMSAzMCA0NQriipwo4oqcKOKLlSniiaBAIC4p4omgQFxuLgoKRG9TdHVmZiDihpAg4omhLy3il6syCgpTb2x2ZU9uZSDihpAgLyviipDiiaEo4oqi4oeMKeKNoijiioI64pahRG9TdHVmZsKw4pah4oqi4oeMLnwv4oal4omgMMKw4pah4oqi4oeMKcKk4pahClNvbHZlVHdvIOKGkCAvLeKHjOKKkOKJoeKKouKNoijiioI64pahRG9TdHVmZsKw4pah4oqi4oeMLnwv4oal4omgMMKw4pah4oqi4oeMKcKk4pahCgomcCZw4oqDKC8r4omhU29sdmVPbmV8LyviiaFTb2x2ZVR3bykK

&fras "input"

⊜(⊜(⋕)≠@ .)≠@\n.

DoStuff ← ≡/-◫2

SolveOne ← /+⊐≡(⊢⇌)⍢(⊂:□DoStuff°□⊢⇌.|/↥≠0°□⊢⇌)¤□
SolveTwo ← /-⇌⊐≡⊢⍢(⊂:□DoStuff°□⊢⇌.|/↥≠0°□⊢⇌)¤□

⊃(/+≡SolveTwo|/+≡SolveOne)
