# uiua repl: https://www.uiua.org/pad?src=0_6_1__JCAwIDMgNiA5IDEyIDE1CiQgMSAzIDYgMTAgMTUgMjEKJCAxMCAxMyAxNiAyMSAzMCA0NQriipwo4oqcKOKLlSniiaBAIC4p4omgQFxuLgoKRG9TdHVmZiDihpAg4omhLy3il6syCgpHZXROZXh0IOKGkCAvK-KKkOKJoSjiiqLih4wp4o2iKOKKgjrilqFEb1N0dWZmwrDilqHiiqLih4wufC_ihqXiiaAwwrDilqHiiqLih4wpwqTilqEKCi8r4omhR2V0TmV4dAo=

&fras "input"

⊜(⊜(⋕)≠@ .)≠@\n.

DoStuff ← ≡/-◫2

SolveOne ← /+⊐≡(⊢⇌)⍢(⊂:□DoStuff°□⊢⇌.|/↥≠0°□⊢⇌)¤□
SolveTwo ← /-⇌⊐≡⊢⍢(⊂:□DoStuff°□⊢⇌.|/↥≠0°□⊢⇌)¤□

⊃(/+≡SolveTwo|/+≡SolveOne)
