# uiua REPL: https://www.uiua.org/pad?src=0_7_0__JCAuLi4jLi4uLi4uCiQgLi4uLi4uLiMuLgokICMuLi4uLi4uLi4KJCAuLi4uLi4uLi4uCiQgLi4uLi4uIy4uLgokIC4jLi4uLi4uLi4KJCAuLi4uLi4uLi4jCiQgLi4uLi4uLi4uLgokIC4uLi4uLi4jLi4KJCAjLi4uIy4uLi4uCgpTSVpFIOKGkCAxMAoKPUAj4oqc4oiY4omgQFxuLgoKRXhwYW5kIOKGkCAoCiAgwqwv4oalLgogICsxXCsKICDDly0xIFNJWkUKICArMeKHoeKnuy4KICArCiAgw5fCpAopCgriioPijZzijYlFeHBhbmQgRXhwYW5kCuKWveKJoDDiiaEv4oalLiDimIcx4o2J4oqfCgriiqAoLyvijLUtKS4Kw7cyLyvima0K

&fras "input"

SIZE ← 1000000

=@#⊜∘≠@\n.

Expand ← (
  ¬/↥.
  +1\+
  ×-1 SIZE
  +1⇡⧻.
  +
  ×¤
)

⊃⍜⍉Expand Expand
▽≠0≡/↥. ☇1⍉⊟

⊠(/+⌵-).
÷2/+♭
