# uiua REPL: https://www.uiua.org/pad?src=0_7_0__JCAuLi4jLi4uLi4uCiQgLi4uLi4uLiMuLgokICMuLi4uLi4uLi4KJCAuLi4uLi4uLi4uCiQgLi4uLi4uIy4uLgokIC4jLi4uLi4uLi4KJCAuLi4uLi4uLi4jCiQgLi4uLi4uLi4uLgokIC4uLi4uLi4jLi4KJCAjLi4uIy4uLi4uCgo9QCPiipziiJjiiaBAXG4uCgpFeHBhbmQg4oaQIOKJoeKWvcKkKzHCrC_ihqUuCgpFeHBhbmQK4o2c4o2JRXhwYW5kCgriiqAoLyvijLUtKS7iipoKw7cyLyvima0K

&fras "input"

=@#⊜∘≠@\n.

Expand ← ≡▽¤+1¬/↥.

Expand
⍜⍉Expand

⊠(/+⌵-).⊚
÷2/+♭
