https://www.uiua.org/pad?src=0_6_1__JCBMTFIKJCAKJCBBQUEgPSAoQkJCLCBCQkIpCiQgQkJCID0gKEFBQSwgWlpaKQokIFpaWiA9IChaWlosIFpaWikKCnJlZ2V4IltBLVpdKyIK4oqDKMKw4pahwrDCpMKwwqTihpkxfOKGmDEpCkluc3RydWN0aW9ucyDihpAKCkhhc2gg4oaQIC8rw5figb86Mjbih4zih6Hip7suIC1AQQpGaW5pc2gg4oaQIEhhc2giWlpaIgoK4oavwq8xXzPiipDiiaEoSGFzaCnCsMKkCk1hcCDihpAKCkdldCDihpAgfDMg4oqPOuKKmSg9QFIp4oaYMeKKj-KKgyjiipc64omh4oqifOKImCkKClNlbGVjdFdpdGhNb2R1bGUg4oaQIOKKj-KKgyjil7_ip7t84oiYKQoKU29sdmVQYXJ0T25lIOKGkCA7OzvijaIoCiAg4oqDKAogICAg4oiYCiAgfCBHZXTiioMo4oqZ4oiYfOKLheKLhVNlbGVjdFdpdGhNb2R1bGUpCiAgfCDii4Xii4XiipkoKzEpCiAgKQp8IOKJoEZpbmlzaDsKKeKKmeKKmeKKmTAKClNvbHZlUGFydE9uZSBNYXAgSGFzaCAiQUFBIiBJbnN0cnVjdGlvbnMK

&fras "input"

regex"[A-Z]+"
⊃(°□°¤°¤↙1|↘1)
Instructions ←

Hash ← /+×ⁿ:26⇌⇡⧻. -@A
Finish ← Hash"ZZZ"

↯¯1_3⊐≡(Hash)°¤
Map ←

Get ← |3 ⊏:⊙(=@R)↘1⊏⊃(⊗:≡⊢|∘)

SelectWithModule ← ⊏⊃(◿⧻|∘)

SolvePartOne ← ;;;⍢(
  ⊃(
    ∘
  | Get⊃(⊙∘|⋅⋅SelectWithModule)
  | ⋅⋅⊙(+1)
  )
| ≠Finish;
)⊙⊙⊙0

SolvePartOne Map Hash "AAA" Instructions
