# uiua REPL: https://www.uiua.org/pad?src=0_7_0__JCA_Pz8uIyMjIDEsMSwzCiQgLj8_Li4_Py4uLj8jIy4gMSwxLDMKJCA_Iz8jPyM_Iz8jPyM_Iz8gMSwzLDEsNgokID8_Pz8uIy4uLiMuLi4gNCwxLDEKJCA_Pz8_LiMjIyMjIy4uIyMjIyMuIDEsNiw1CiQgPyMjIz8_Pz8_Pz8_IDMsMiwxCgriipwo4pahKeKJoEBcbi4KClByb2Nlc3Mg4oaQICgKICDiipkoLysuKQoKICDip7vilr09QD8uLgoKICA64ouv4oeh4oG_OjIKCiAgOuKKgygtLys9QCPiipnii4XiiJh84oqZ4oqZ4oiYKQogIOKKmSgKICAgIDoKICAgIOKKgyg94omhLyt84oiYKQogICAg4pa9CiAgKQoKICA9QD8uCgogIOKIqcKkCgogIOKJoSjijZwowrDilqHiiqLih4ziipXilqEpKChALnxAIykuOykpCiAg4oqZ4ouF4ouF4oiYCiAg4oqZwqQKICAvK-KJoSgKICAgIOKKnOKnu-KJoEAuLgogICAg4omNCiAgKQopCgovK-KJoShQcm9jZXNzIDriipko4oaYwq8xKeKKnOKLleKJoEAsLuKKg-KGmOKGmSsx4oqXQCAuwrDilqEpCg==

&fras "input"

⊜(□)≠@\n.

Process ← (
  ⊙(/+.)

  ⧻▽=@?..

  :⋯⇡ⁿ:2

  :⊃(-/+=@#⊙⋅∘|⊙⊙∘)
  ⊙(
    :
    ⊃(=≡/+|∘)
    ▽
  )

  =@?.

  ∩¤

  ≡(⍜(°□⊢⇌⊕□)((@.|@#).;))
  ⊙⋅⋅∘
  ⊙¤
  /+≡(
    ⊜⧻≠@..
    ≍
  )
)

/+≡(Process :⊙(↘¯1)⊜⋕≠@,.⊃↘↙+1⊗@ .°□)
